<a href="https://colab.research.google.com/github/Muskan-Sh-23/Machine-learning/blob/main/Preceptron_using_Sklearn/Perceptron_using_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
#Import the data and check it
df = pd.read_csv('/content/collegePlace.csv')
df.head()

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot
0,22,Male,Electronics And Communication,1,8,1,1,1
1,21,Female,Computer Science,0,7,1,1,1
2,22,Female,Information Technology,1,6,0,0,1
3,21,Male,Information Technology,0,8,0,1,1
4,22,Male,Mechanical,0,8,1,0,1

In [ ]:
df.shape

(2966, 8)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
encoded = enc.fit_transform(df[['Gender']])
encoded = encoded.toarray()
encoded

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [ ]:
encoded = enc.fit_transform(df[['Stream']])
encoded = encoded.toarray()
encoded

array([[0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [ ]:
encoded_df = pd.DataFrame(encoded, columns=enc.get_feature_names_out(['Stream']))

In [ ]:
dataset_encoded = pd.concat([df.drop('Stream', axis = 1), encoded_df], axis=1)
dataset_encoded

,Age,Gender,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot,Stream_Civil,Stream_Computer Science,Stream_Electrical,Stream_Electronics And Communication,Stream_Information Technology,Stream_Mechanical
0,22,Male,1,8,1,1,1,0.0,0.0,0.0,1.0,0.0,0.0
1,21,Female,0,7,1,1,1,0.0,1.0,0.0,0.0,0.0,0.0
2,22,Female,1,6,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0
3,21,Male,0,8,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0
4,22,Male,0,8,1,0,1,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,23,Male,0,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
2962,23,Male,1,7,1,0,0,0.0,0.0,0.0,0.0,0.0,1.0
2963,22,Male,1,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
2964,22,Male,1,7,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
2965,23,Male,0,8,0,0,1,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
gender_encoded = pd.get_dummies(dataset_encoded['Gender'], drop_first = True)
dataset_encoded = pd.concat([dataset_encoded, gender_encoded], axis=1)
dataset_encoded = dataset_encoded.drop('Gender', axis=1)
dataset_encoded

,Age,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot,Stream_Civil,Stream_Computer Science,Stream_Electrical,Stream_Electronics And Communication,Stream_Information Technology,Stream_Mechanical,Male
0,22,1,8,1,1,1,0.0,0.0,0.0,1.0,0.0,0.0,True
1,21,0,7,1,1,1,0.0,1.0,0.0,0.0,0.0,0.0,False
2,22,1,6,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0,False
3,21,0,8,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0,True
4,22,0,8,1,0,1,0.0,0.0,0.0,0.0,0.0,1.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,23,0,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,True
2962,23,1,7,1,0,0,0.0,0.0,0.0,0.0,0.0,1.0,True
2963,22,1,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,True
2964,22,1,7,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,True
2965,23,0,8,0,0,1,1.0,0.0,0.0,0.0,0.0,0.0,True

In [ ]:
X = data.drop('PlacedOrNot', axis=1)
y = data['PlacedOrNot']

In [ ]:
#Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = Perceptron()
model.fit(X_train, y_train)

Perceptron()

In [ ]:
#Predict the value
Y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, Y_pred))

Accuracy: 0.7255892255892256