<a href="https://colab.research.google.com/github/Muskan-Sh-23/Machine-learning/blob/main/Decision_Tree/Decision_Tree_using_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
#Import the dataset and check it
dataset = pd.read_csv('/content/collegePlace.csv')
dataset

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot
0,22,Male,Electronics And Communication,1,8,1,1,1
1,21,Female,Computer Science,0,7,1,1,1
2,22,Female,Information Technology,1,6,0,0,1
3,21,Male,Information Technology,0,8,0,1,1
4,22,Male,Mechanical,0,8,1,0,1
...,...,...,...,...,...,...,...,...
2961,23,Male,Information Technology,0,7,0,0,0
2962,23,Male,Mechanical,1,7,1,0,0
2963,22,Male,Information Technology,1,7,0,0,0
2964,22,Male,Computer Science,1,7,0,0,0
2965,23,Male,Civil,0,8,0,0,1

In [ ]:
dataset.shape

(2966, 8)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
encoded = enc.fit_transform(dataset[['Gender']])
encoded = encoded.toarray()
encoded

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [ ]:
encoded = enc.fit_transform(dataset[['Stream']])
encoded = encoded.toarray()
encoded

array([[0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [ ]:
encoded_df = pd.DataFrame(encoded, columns=enc.get_feature_names_out(['Stream']))

In [ ]:
dataset_encoded = pd.concat([dataset.drop('Stream', axis = 1), encoded_df], axis=1)
dataset_encoded

,Age,Gender,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot,Stream_Civil,Stream_Computer Science,Stream_Electrical,Stream_Electronics And Communication,Stream_Information Technology,Stream_Mechanical
0,22,Male,1,8,1,1,1,0.0,0.0,0.0,1.0,0.0,0.0
1,21,Female,0,7,1,1,1,0.0,1.0,0.0,0.0,0.0,0.0
2,22,Female,1,6,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0
3,21,Male,0,8,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0
4,22,Male,0,8,1,0,1,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,23,Male,0,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
2962,23,Male,1,7,1,0,0,0.0,0.0,0.0,0.0,0.0,1.0
2963,22,Male,1,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
2964,22,Male,1,7,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
2965,23,Male,0,8,0,0,1,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
dataset_encoded = pd.concat([dataset.drop('Gender', axis = 1), encoded_df], axis=1)
dataset_encoded

,Age,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot,Stream_Civil,Stream_Computer Science,Stream_Electrical,Stream_Electronics And Communication,Stream_Information Technology,Stream_Mechanical
0,22,Electronics And Communication,1,8,1,1,1,0.0,0.0,0.0,1.0,0.0,0.0
1,21,Computer Science,0,7,1,1,1,0.0,1.0,0.0,0.0,0.0,0.0
2,22,Information Technology,1,6,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0
3,21,Information Technology,0,8,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0
4,22,Mechanical,0,8,1,0,1,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,23,Information Technology,0,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
2962,23,Mechanical,1,7,1,0,0,0.0,0.0,0.0,0.0,0.0,1.0
2963,22,Information Technology,1,7,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
2964,22,Computer Science,1,7,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
2965,23,Civil,0,8,0,0,1,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
dataset_encoded = pd.get_dummies(dataset_encoded)

In [ ]:
X =dataset_encoded.drop('PlacedOrNot',axis=1).values
Y = dataset_encoded['PlacedOrNot'].values

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
model = DecisionTreeClassifier()
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
accuracy

0.8872053872053872